[project]
name = 'Tokenized-Sustainable-Seafood-Certification'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.harvesting-method]
path = 'contracts/harvesting-method.clar'
clarity_version = 2
epoch = 2.5

[contracts.producer-verification]
path = 'contracts/producer-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
